server:
  port: 8083

spring:
  application:
    name: analysis-service
  kafka:
    bootstrap-servers: kafka:9092
  data:
    redis:
      host: redis
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.loganalyzer: DEBUG
