server:
  port: 8082

spring:
  application:
    name: stream-processor-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    streams:
      application-id: stream-processor-service-v3
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        commit.interval.ms: 1000

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info,bindings
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
