server:
  port: 8084

spring:
  application:
    name: search-service
  elasticsearch:
    uris: http://elasticsearch:9200

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.loganalyzer: DEBUG
